### ISSUE TITLE
アプリの説明文を考える

### ISSUE THREAD

**Issue by endows** [konojunya/booksharing#11]

**Comment by endows** [comment]
![2015-08-25 9 50 26](https://cloud.githubusercontent.com/assets/12727560/9456141/ca229bfa-4b0e-11e5-9037-b7d28d4517b5.png)
アプリのトップに表示するような説明文を考えてもらいたい。難しいなら僕がやるよ

**Comment by endows** [comment]
書く内容は以下
- タイトル
- 一行の説明
- 特徴を２−３個　一文で

なんてどうでしょう。自分なりに変えてもいいよ

**Comment by endows** [comment]
実際に作るUI、みたいなのは、CSSで直接作ってもいい。ただ、せっかくMaterilaUIしてるから、できればMaterialUIを使いこなせるようになったあとでレイアウトを組んでみたらいいんじゃないかと思う。

**Comment by konojunya** [comment]
了解です！
文考えときます
