### ISSUE TITLE
ミッション:Reactを導入せよ

### ISSUE THREAD

**Issue by endows** [konojunya/booksharing#4]
http://react-in-meteor.readthedocs.org/en/latest/
このサイトをみて、meteor内で`React`コマンドを使えるようにしてみて。

**Comment by konojunya** [comment]
![2015-08-23 13 04 53](https://cloud.githubusercontent.com/assets/12035578/9426905/29b9a38c-4999-11e5-9696-9eab24879fa6.png)

**Comment by endows** [comment]
完璧です！
